config/routes.rb
Cetf::Application.routes.draw do

  resources :participants

  resources :challenges do
    post 'solve', :on => :member
    post 'writeup', :on => :member
    get 'writeups', :on => :member
  end

  resources :attachments

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'root#index'
end

app/models/participant.rb
class Participant < ActiveRecord::Base

  has_many :challenges, :foreign_key => :author_id
  has_many :solutions, :dependent => :destroy
  has_many :solved_challenges, :through => :solutions, :source => :challenge

  validates :uid, :uniqueness => {:scope => :provider, :message => "already registered!"}

  def self.names_ids
    participants = []
    Participant.select('id, name').each do |a|
      participants << [a.name, a.id]
    end
    return participants
  end

  def self.create_with_omniauth(auth)
    create! do |participant|
      participant.provider = auth["provider"]
      participant.uid = auth["uid"]
      participant.name = auth["info"]["name"]
      # TODO: check oauth field
      participant.email = auth["info"]["email"]
      participant.policy_new_challenge = true
      participant.policy_challenge_solved = true
      participant.points = 0
    end
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def index
    @participants = Participant.order("points DESC").all
  end

  def edit
    @owner = is_owner? params[:id].to_i
    if !@owner
      flash[:error] = "You don't have the permission to do that :\\"
      redirect_to root_url
    end
    @participant = current_participant
  end

  def show
    @participant = Participant.find(params[:id])
    @owner = is_owner? params[:id].to_i
  end

  def update
    if !is_owner? params[:id].to_i
      flash[:error] = "An error occurred while updating the profile information"
      redirect_to root_url
    end
    participant = current_participant
    participant.name = params[:participant][:name]
    participant.policy_new_challenge = params[:participant][:policy_new_challenge]
    participant.policy_challenge_solved = params[:participant][:policy_challenge_solved]
    participant.save!
    redirect_to participants_path
  end

  def destroy
    if !is_owner? params[:id].to_i
      flash[:error] = "An error occurred while deleting the profile"
      redirect_to root_url
    end
    participant = current_participant
    participant.destroy
    reset_session
    redirect_to root_url
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

  private

  def is_owner?(id)
    !current_participant.nil? && (current_participant.id == id)
  end
end

app/views/participants/edit.html.haml
%div.page-header
  %h2 Edit your profile information

= form_tag participant_path(@participant.id), :method => :put, :class => "form-horizontal" do
  %fieldset
    %div.control-group
      = label :participant, :name, 'Your Name', :class => "control-label"
      %div.controls
        = text_field :participant, :name, :class => "input-xlarge"
    %div.control-group
      = label :participant, :email, 'Your Email', :class => "control-label"
      %div.controls
        = text_field :participant, :email, :class => "input-xlarge", :disabled => true
    %div.control-group
      = label :participant, :policy, 'Email policies:', :class => "control-label"
      %div.controls
        %label.checkbox
          = check_box :participant, :policy_new_challenge
          Receive an email when a new challenge is inserted.
        %label.checkbox
          = check_box :participant, :policy_challenge_solved
          Receive an email when someone solve one of your challenges.

    %div.form-actions
      = submit_tag 'Edit', :class => "btn btn-primary"
      = link_to 'Cancel', participant_path(@participant.id), :class => "btn"

= button_to 'Delete your profile', participant_path(@participant.id), :method => :delete, :confirm => 'Are you sure you want to delete your profile?', :class => "btn btn-danger"

app/views/participants/index.html.haml
%div.hero-unit
  %h2 Participants
  %p A participant can solve and write new challenges!
  - if current_participant.nil?
    = link_to 'Login now with google, facebook or twitter!', login_path, :class => "btn btn-primary btn-large"
  -else
    = link_to 'See your profile!', participant_path(current_participant.id), :class => "btn btn-primary btn-large"

%table{:id => "participants", :class => "table table-striped table-bordered"}
  %thead
    %tr
      %th Name
      %th Points
  %tbody{ "data-provides" => "rowlink"}
    - @participants.each do |part|
      %tr
        %td
          = link_to "", participant_path(part.id)
          %span.link= part.name
        %td= part.points

app/views/participants/show.html.haml
%div.page-header
  %h2
    =@participant.name
    -if @owner
      %small
        =" ["
        =link_to "Edit", edit_participant_path(@participant.id)
        ]
  %p= "Total points: #{@participant.points}"

%div{:class => "container-fluid"}
  %div{:class => "row-fluid"}
    %div{:class => "span6 well"}
      %h4 CHALLENGES CREATED
      %ul{:class => "nav nav-list"}
        - @participant.challenges.each do |c|
          %li= link_to "#{c.name} [#{c.category} - #{c.points} pts]", challenge_path(c.id)
    %div{:class => "span6 well"}
      %h4 CHALLENGES SOLVED
      %ul{:class => "nav nav-list"}
        - @participant.solved_challenges.each do |c|
          %li= link_to "#{c.name} [#{c.category} - #{c.points} pts]", challenge_path(c.id)

%hr

= link_to 'Back to Participants', participants_path, :class => "btn btn-large"