config/routes.rb
Cetf::Application.routes.draw do

  resources :participants

  resources :challenges do
    post 'solve', :on => :member
    post 'writeup', :on => :member
    get 'writeups', :on => :member
  end

  resources :attachments

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'root#index'
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

  cattr_reader :pointsPerChallengeInsertion
  @@pointsPerChallengeInsertion = 10

  has_many :solutions, :dependent => :destroy
  has_many :solvers, :through => :solutions, :source => :participant
  belongs_to :author, :class_name => "Participant"
  has_many :attachments, :dependent => :destroy

  validates :points, :presence => { :message => "is mandatory" }, :numericality => {:only_integer => true, :greater_than => 0, :message => "must be a number grather than 0" }
  validates :name, :uniqueness => { :message => "already exists!" }, :presence => { :message => "can't be blank"}
  validates :category, :solution, :text, :presence => {:message => "can't be blank"}

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def index
    @challenges = Challenge.order("points DESC").all
    @logged = logged?
  end

  def writeup
    if !logged?
      redirect_to challenge_path(params[:id])
    end
    solver = current_participant
    @challenge = Challenge.find(params[:id])
    solution = @challenge.solutions.where('participant_id = ?', current_participant.id).first
    if !solution.nil?
      solution.writeup = params[:solution][:writeup]
      solution.save!
      flash[:notice] = "Your writeup has been saved!"
    else
      flash[:error] = "You haven't solved this challenge!! D:"
    end
    redirect_to challenge_path(@challenge.id)
  end

  def writeups
    @challenge = Challenge.find(params[:id])
    @solutions = @challenge.solutions.where('writeup <> ""')
  end

  def solve
    if !logged?
      flash[:error] = "You must be logged in order to solve challenges."
      redirect_to challenge_path(params[:id])
    end
    @challenge = Challenge.find(params[:id])
    solver = current_participant
    if @challenge.author === solver
      flash[:error] = "You have created the challenge!! :/"
    elsif @challenge.solvers.include? solver
      flash[:error] = "Yo have already solved this challenge!! D:"
    elsif @challenge.solution === params[:solution][:solution]
      solver.points += @challenge.points
      solver.save!
      @challenge.solvers << solver
      @challenge.save!
      if !@challenge.author.nil?
        SystemMailer.challenge_solved(solver, @challenge).deliver
      end
      flash[:notice] = "Congratz #{solver.name}!!! +#{@challenge.points} points! :D"
    else
      flash[:error] = "Wrong solution... :("
    end
    redirect_to challenge_path(@challenge.id)
  end

  def show
    id = params[:id]
    @challenge = Challenge.find(id)
    @participant = current_participant

    @own = !@challenge.author.nil? && !@participant.nil? && (@challenge.author.id == current_participant.id)

    @there_are_writeups = !@challenge.solutions.where('writeup <> ""').empty?

    @solved = @challenge.solvers.include? current_participant
    @logged = logged?
    if @solved
      @solution = @challenge.solutions.where('participant_id = ?', current_participant.id).first
      @there_are_other_writeups = !@challenge.solutions.where('writeup <> "" AND participant_id <> ?', current_participant.id).empty?
    end

  end

  def destroy
    if !logged?
      redirect_to challenge_path(params[:id])
      return
    end

    @challenge = Challenge.find(params[:id])
    if @challenge.author.nil? or @challenge.author.id != current_participant.id
      flash[:error] = "You must be the author in order to delete the challenge"
      redirect_to challenges_path(params[:id])
      return
    end
    points = @challenge.points
    old_solvers = @challenge.solvers

    old_solvers.each do |s|
      s.points -= points
      s.points = 0 unless s.points > 0
      s.save
    end

    author = @challenge.author
    if !author.nil?
      author.points -= Challenge.pointsPerChallengeInsertion
      author.points = 0 unless author.points > 0
      author.save
    end

    @challenge.destroy

    flash[:notice] = "Challenge '#{@challenge.name}' deleted."
    redirect_to challenges_path
  end

  def edit
    if !logged?
      redirect_to challenge_path(params[:id])
      return
    end
    @challenge = Challenge.find(params[:id])
    if @challenge.author.nil? or current_participant.id != @challenge.author.id
      redirect_to challenge_path(params[:id])
    end
  end

  def new
    if !logged?
      redirect_to challenges_path
      return
    end
    @challenge = Challenge.new()
  end

  def update
    if !logged?
      redirect_to challenge_path(params[:id])
      return
    end
    begin

      files = save_files

      @challenge = Challenge.find(params[:id])
      fill_challenge
      @challenge.save!

      rem_files = []
      if !params[:rem_attachments].nil?
        params[:rem_attachments].each do |id, val|
          if val == "0"
            begin
              oldfile = Attachment.where("challenge_id = ? AND id = ?", @challenge.id, id.to_i).first
              oldfile.destroy unless oldfile.nil?
            rescue
            end
          end
        end
      end

      create_attachments files, @challenge.id

      flash[:notice] = "#{@challenge.name} was successfully updated."
      redirect_to challenges_path
    rescue Exception => e
      rollbackUpload files
      flash[:error] = "Error updating the challenge: #{e.message}"
      redirect_to challenges_path
      return
    end
  end

  def create
    if !logged?
      flash[:error] = "You must be logged in order to insert new challenges"
      redirect_to challenges_path
      return
    end
    begin

      if !verify_recaptcha
        flash[:error] = "Sorry wrong captcha!"
        @challenge = Challenge.new()
        fill_challenge
        render :action => :new
        return
      end

      files = save_files

      @challenge = Challenge.new()
      fill_challenge
      @challenge.save!

      create_attachments files, @challenge.id

      @challenge.author.points += Challenge.pointsPerChallengeInsertion
      @challenge.author.save

      Participant.all.each do |p|
        if p.id != @challenge.author.id
          SystemMailer.new_challenge(p, @challenge).deliver
        end
      end
      flash[:notice] = "#{@challenge.name} was successfully created. +10 points :)"
      redirect_to challenges_path
    rescue Exception => e
      @challenge.destroy unless @challenge.nil?
      begin
        rollbackUpload files
        flash[:error] = "Error creating challenge: #{e.message}"
      rescue Exception => e1
        flash[:error] = "Error creating challenge: #{e.message}, #{e1.message}"
      end
      redirect_to new_challenge_path
    end
  end

  private

  def save_files
      files = []
      if !params[:attachments].nil?
        raise "Files too big (max allowed size is 5MB)" unless Attachment.check_size(params[:attachments])
        params[:attachments].each do |id, file|
          res = Attachment.save(id, file)
          files << res unless res.nil?
        end
      end
      return files
  end

  def fill_challenge
      @challenge.name = params[:challenge][:name]
      @challenge.text = params[:challenge][:text]
      @challenge.solution = params[:challenge][:solution]
      @challenge.author = current_participant
      @challenge.points = params[:challenge][:points]
      @challenge.category = params[:challenge][:category]
  end

  def create_attachments files, id
      files.each do |f|
        next if f.nil?
        @attachment = Attachment.new()
        @attachment.challenge_id = id
        @attachment.file = f[:file]
        @attachment.name = f[:name]
        @attachment.save!
      end
  end

  def logged?
    return !current_participant.nil?
  end

  def rollbackUpload files
    return if files.nil?
    error = ""
    files.each do |f|
      begin
        Attachment.remove(f[:name])
      rescue Exception => e
        error += e.message + " "
      end
    end
    raise Exception, error unless error == ""
  end

end

app/views/challenges/edit.html.haml
%div.page-header
  %h2 Edit the challenge

= form_tag challenge_path(@challenge.id), :multipart => true, :method => :put, :class => "form-horizontal" do
  %fieldset
    %div.control-group
      = label :challenge, :name, 'Challenge Name', :class => "control-label"
      %div.controls
        = text_field :challenge, :name, :class => "input-xlarge"

    %div.control-group
      = label :challenge, :points, 'Challenge points', :class => "control-label"
      %div.controls
        = number_field :challenge, :points

    %div.control-group
      = label :challenge, :category, 'Category', :class => "control-label"
      %div.controls
        = text_field :challenge, :category

    %div.control-group
      = label :challenge, :text, 'Challenge text', :class => "control-label"
      %div.controls
        = text_area :challenge, :text, :class => "input-xlarge"

    %div.control-group
      = label :challenge, :solution, 'Solution (Flag)', :class => "control-label"
      %div.controls
        = text_field :challenge, :solution

    - if !@challenge.attachments.empty?
      %div.control-group
        = label :rem_attachments, 'Uncheck to delete an attachment', :class => "control-label"
        %div.controls
          - @challenge.attachments.each do |a|
            %label.checkbox
              = check_box :rem_attachments, a.id, :checked => true
              = File.basename(a.file)

    %div.control-group#add_div
      %div.controls
        %input{:type => "button" , :id => "add_button", :class => "btn", :value => "Add another attachment" }

    %div{:class => "form-actions"}
      = submit_tag 'Update', :class => "btn btn-primary btn-large"
      = link_to 'Cancel', challenge_path(@challenge.id), :class => "btn btn-large"


= button_to 'Delete the challenge', challenge_path(@challenge.id), :method => :delete, :confirm => 'Are you sure you want to delete your challenge?', :class => "btn btn-danger btn-large"

app/views/challenges/index.html.haml
%div.hero-unit
  %h2 Challenges
  %p Click on a challenge and try to solve it! Or contribute to the CeTF creating a new one.
  %p Note that every challenge and the respective attachments are under GNU GPL 3.0 license.
  - if @logged
    = link_to 'Create a new challenge', new_challenge_path, :class => "btn btn-primary btn-large"
  - else
    = link_to 'Login to create a challenge', login_path, :class => "btn btn-primary btn-large"

%table{:id => "challenges", :class => "table table-striped table-bordered",}
  %thead
    %tr
      %th Title
      %th Points
      %th Category
      %th Author
      %th Solved
  %tbody{ "data-provides" => "rowlink"}
    - @challenges.each do |c|
      - if c.solvers.include? current_participant
        - @row = "success"
      - elsif !c.author.nil? and c.author == current_participant
        - @row = "warning"
      - else
        - @row = ""
      %tr{:class => @row}
        %td
          =link_to "", challenge_path(c), :class => "rowlink"
          %span.link= c.name
        %td= c.points
        %td= c.category
        %td
          -if !c.author.nil?
            =c.author.name
          -else
            ='-'
        %td= c.solvers.length

app/views/challenges/new.html.haml
%div.page-header
  %h2 Insert a new Challenge!

= form_tag challenges_path, :multipart => true, :method => :post, :class => "form-horizontal" do
  %fieldset
    %div.control-group
      = label :challenge, :name, 'Challenge Name', :class => "control-label"
      %div.controls
        = text_field :challenge, :name, :class => "input-xlarge"

    %div.control-group
      = label :challenge, :points, 'Challenge points', :class => "control-label"
      %div.controls
        = number_field :challenge, :points

    %div.control-group
      = label :challenge, :category, 'Category', :class => "control-label"
      %div.controls
        = text_field :challenge, :category

    %div.control-group
      = label :challenge, :text, 'Challenge text', :class => "control-label"
      %div.controls
        = text_area :challenge, :text, :class => "input-xlarge"

    %div.control-group
      = label :challenge, :solution, 'Solution (Flag)', :class => "control-label"
      %div.controls
        = text_field :challenge, :solution

    %div.control-group#add_div
      %div.controls
        %input{:type => "button" , :id => "add_button", :class => "btn", :value => "Add another attachment" }

    = recaptcha_tags :ssl => true

    %div.form-actions
      = submit_tag 'Create', :class => "btn btn-primary"
      = link_to 'Cancel', challenges_path, :class => "btn"

app/views/challenges/show.html.haml
%div.page-header
  %h2
    = @challenge.name
    - if !@challenge.author.nil?
      %small= " by " + @challenge.author.name
  %p="#{@challenge.category} challenge, #{@challenge.points} pts"

%div{:class => "container-fluid"}
  %div{:class => "row-fluid well"}
    %div{:class => "span7"}
      %p= @challenge.text.gsub(/\n/, '<br/>').html_safe
    %div{:class => "span4 divider"}
      %ul{:class => "nav nav-list"}
        %li.nav-header ATTACHMENTS
        - @challenge.attachments.each do |a|
          %li=link_to a.name, attachment_path(a.id)
        %li.nav-header SOLVED BY
        - @challenge.solvers.each do |a|
          %li=link_to "#{a.name}", participant_path(a.id)

  %div{:class => "row-fluid "}
    %div.span3
      = button_to 'Challenges List', challenges_path, :method => :get, :class => "btn btn-large"
    -if @there_are_writeups
      -if @there_are_other_writeups
        %div.span3
          =button_to "Show Other Writeups", writeups_challenge_path(@challenge.id), :class => "btn btn-primary btn-large", :method => "get"
      - elsif @own
        %div.span3
          =button_to "Show Writeups", writeups_challenge_path(@challenge.id), :class => "btn btn-primary btn-large", :method => "get"
      - elsif !@solved & @logged
        %div.span3
          =button_to "Show Writeups", writeups_challenge_path(@challenge.id), :class => "btn btn-danger btn-large", :confirm => "Are you giving up?", :method => "get"

    -if @own
      %div.span3
        = button_to 'Edit the challenge', edit_challenge_path(@challenge.id), :method => :get, :class => "btn btn-primary btn-large"
      %div.span3
        = button_to 'Delete the challenge', challenge_path(@challenge.id), :method => :delete, :confirm => 'Are you sure you want to delete your challenge?', :class => "btn btn-danger btn-large"

  %div{:class => "row-fluid "}

    -if @solved
      = form_tag writeup_challenge_path(@challenge), :method => :post, :class => "form-horizzontal" do
        %fieldset
          %legend
            -if @solution.writeup.nil? | @solution.writeup.empty?
              Write your own writeup!
            -else
              Edit your writeup!
          %div.control-group
            %div.controls
              = text_area :solution, :writeup, :class => "input-xlarge"

          %div.form-actions
            = submit_tag 'Save', :class => "btn btn-primary btn-large"
            = link_to 'Discard changes', challenge_path(@challenge),  :class => "btn btn-large"
    - elsif !@own & @logged
      = form_tag solve_challenge_path(@challenge), :method => :post, :class => "form-horizontal" do
        %fieldset
          %legend Submit a solution!

          %div.control-group
            = label :solution, :solution, 'Solution:', :class => "control-label"
            %div.controls
              = text_field :solution, :solution, :class => "input-xlarge"
              %p.help-block Insert the flag obtained solving the challenge

          %div.form-actions
            = submit_tag 'Submit solution', :class => "btn btn-primary btn-large"

app/views/challenges/writeups.html.haml
%div.page-header
  %h2
    = @challenge.name
    - if !@challenge.author.nil?
      %small= " by " + @challenge.author.name
  %p="#{@challenge.category} challenge, #{@challenge.points} pts"

%div{:class => "container-fluid"}
  %div{:class => "row-fluid well"}
    %div{:class => "span7"}
      %p= @challenge.text
    %div{:class => "span4 divider"}
      %ul{:class => "nav nav-list"}
        %li.nav-header ATTACHMENTS
        - @challenge.attachments.each do |a|
          %li=link_to a.name, attachment_path(a.id)
        %li.nav-header SOLVED BY
        - @challenge.solvers.each do |a|
          %li=link_to "#{a.name}", participant_path(a.id)

  %div{:class => "row-fluid "}
    %div.span3
      = button_to 'Back to Challenge', challenge_path(@challenge.id), :method => :get, :class => "btn btn-large"

  -@solutions.each_slice(2) do |as|
    %div{:class => "row-fluid"}
      - as.each do |s|
        %div{:class => "span6 well"}
          %h3=s.participant.name
          %p=s.writeup