config/routes.rb
Cetf::Application.routes.draw do

  resources :participants

  resources :challenges do
    post 'solve', :on => :member
    post 'writeup', :on => :member
    get 'writeups', :on => :member
  end

  resources :attachments

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'root#index'
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title CeTF - CeSeNA CTF
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %div{:class=>"navbar navbar-inverse navbar-fixed-top"}
      %div.navbar-inner
        %div.container-fluid
          = link_to "CeTF - The open CeSeNA CTF", root_url, :class=>"brand"
          %ul.nav
            - if params[:controller] === "participants"
              %li= link_to "Home", root_url
              %li= link_to "Challenges", challenges_path
              %li.active= link_to "Participants", participants_path
            - elsif params[:controller] === "challenges"
              %li= link_to "Home", root_url
              %li.active= link_to "Challenges", challenges_path
              %li= link_to "Participants", participants_path
            - else
              %li.active= link_to "Home", root_url
              %li= link_to "Challenges", challenges_path
              %li= link_to "Participants", participants_path
          %p{ :class=>"navbar-text pull-right"}
            -if current_participant.nil?
              =link_to "Login", login_path, :class=>"navbar-link"
            -else
              Logged in as
              =link_to current_participant.name, participant_path(current_participant.id), :class=>"navbar-link"
              %small
                =" ["
                =link_to "logout", logout_path, :class=>"navbar-link"
                ]

    %div.container-fluid
      %div.span12
        - if flash[:notice]
          %div{:class => "alert alert-info"}
            =flash[:notice]
        - if flash[:error]
          %div{:class => "alert alert-error"}
            =flash[:error]
        = yield